services:
  tests:
    build: .
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - EMAIL2=${EMAIL2}
      - PASSWORD2=${PASSWORD2}
    volumes:
      - ./tests/allure-results:/app/tests/allure-results