name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  #build:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # container:
    #   image: mcr.microsoft.com/playwright/python:v1.51.0-noble
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.2
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: Run tests
      #   env:
      #     EMAIL: ${{ secrets.EMAIL }}
      #     PASSWORD: ${{ secrets.PASSWORD }}
      #     EMAIL2: ${{ secrets.EMAIL2 }}
      #     PASSWORD2: ${{ secrets.PASSWORD2 }}
      #   run: pytest -c tests/pytest.ini -s -v
      - name: Run tests in Docker
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAIL2: ${{ secrets.EMAIL2 }}
          PASSWORD2: ${{ secrets.PASSWORD2 }}
        run: docker-compose up --build --exit-code-from tests #service name
      - name: Upload allure report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure_report
          path: tests/allure-results/
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: tests/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history