name: CI test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
      - uses: actions/checkout@v4.2.2
      - name: Setup Python
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.11'
      - name: Run python CI test script
        run: python tests/main.py
